// Code generated by mockery v2.30.10. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConfigWriter is an autogenerated mock type for the ConfigWriter type
type ConfigWriter struct {
	mock.Mock
}

// WriteConfig provides a mock function with given fields: _a0
func (_m *ConfigWriter) WriteConfig(_a0 interface{}) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConfigWriter creates a new instance of ConfigWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigWriter {
	mock := &ConfigWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
