// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "github.com/canonical/microceph/microceph/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// GroupedServiceQueryIntf is an autogenerated mock type for the GroupedServiceQueryIntf type
type GroupedServiceQueryIntf struct {
	mock.Mock
}

// AddNew provides a mock function with given fields: ctx, s, service, groupID, groupConfig, serviceInfo
func (_m *GroupedServiceQueryIntf) AddNew(ctx context.Context, s interfaces.StateInterface, service string, groupID string, groupConfig interface{}, serviceInfo interface{}) error {
	ret := _m.Called(ctx, s, service, groupID, groupConfig, serviceInfo)

	if len(ret) == 0 {
		panic("no return value specified for AddNew")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.StateInterface, string, string, interface{}, interface{}) error); ok {
		r0 = rf(ctx, s, service, groupID, groupConfig, serviceInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveForHost provides a mock function with given fields: ctx, s, service, groupID
func (_m *GroupedServiceQueryIntf) RemoveForHost(ctx context.Context, s interfaces.StateInterface, service string, groupID string) error {
	ret := _m.Called(ctx, s, service, groupID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveForHost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.StateInterface, string, string) error); ok {
		r0 = rf(ctx, s, service, groupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGroupedServiceQueryIntf creates a new instance of GroupedServiceQueryIntf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupedServiceQueryIntf(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupedServiceQueryIntf {
	mock := &GroupedServiceQueryIntf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
