// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	state "github.com/canonical/microcluster/v2/state"

	types "github.com/canonical/microceph/microceph/api/types"
)

// ServiceQueryInterface is an autogenerated mock type for the ServiceQueryInterface type
type ServiceQueryInterface struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx, s
func (_m *ServiceQueryInterface) List(ctx context.Context, s state.State) (types.Services, error) {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 types.Services
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, state.State) (types.Services, error)); ok {
		return rf(ctx, s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, state.State) types.Services); ok {
		r0 = rf(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Services)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, state.State) error); ok {
		r1 = rf(ctx, s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceQueryInterface creates a new instance of ServiceQueryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceQueryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceQueryInterface {
	mock := &ServiceQueryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
