#!/bin/bash -eux

# This file is part of MicroCeph - Ceph for a one-rack cluster and appliances.
# Copyright 2021 Canonical Ltd.
# 
# MicroCeph is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 3, as published by the
# Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranties of MERCHANTABILITY,
# SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

CLUSTER=ceph
ID=$(hostname -s)
SERVICE=$(basename $0)

$SNAP/usr/bin/$SERVICE -f --cluster $CLUSTER --id $ID
