name: microceph
base: core22
version: git
grade: stable
source-code: https://github.com/canonical/microceph.git
summary: Simple clustered Ceph deployment
description: |-
 Self-contained self-deployment with clustering.

confinement: strict

environment:
  LD_LIBRARY_PATH: $SNAP/lib:$SNAP/lib/$CRAFT_ARCH_TRIPLET:$SNAP/lib/$CRAFT_ARCH_TRIPLET/ceph:$SNAP/lib:$SNAP/lib/$CRAFT_ARCH_TRIPLET:$SNAP/lib/$CRAFT_ARCH_TRIPLET/ceph:$SNAP/lib/$CRAFT_ARCH_TRIPLET/ceph/compressor:$SNAP/lib/$CRAFT_ARCH_TRIPLET/ceph/crypto:$SNAP/lib/$CRAFT_ARCH_TRIPLET/ceph/erasure-code
  PYTHONPATH: $SNAP/lib/python3/dist-packages

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/ceph:
    symlink: $SNAP/lib/$CRAFT_ARCH_TRIPLET/ceph
  /usr/lib/$CRAFT_ARCH_TRIPLET/rados-classes:
    symlink: $SNAP/lib/$CRAFT_ARCH_TRIPLET/rados-classes
  /etc/ceph:
    bind: $SNAP_DATA/conf
  /usr/share/ceph:
    bind: $SNAP/share/ceph
  /var/lib/ceph:
    bind: $SNAP_COMMON/data
  /var/log/ceph:
    bind: $SNAP_COMMON/logs

apps:
  # Service
  daemon:
    command: commands/daemon.start
    daemon: simple
    plugs:
      - block-devices
      - hardware-observe
      - network
      - network-bind
    slots:
      - microceph
  mds:
    command: commands/mds.start
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  mon:
    command: commands/mon.start
    daemon: simple
    install-mode: disable
    plugs:
      - hardware-observe
      - network
      - network-bind
  mgr:
    command: commands/mgr.start
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  osd:
    command: commands/osd.start
    reload-command: commands/osd.reload
    daemon: simple
    install-mode: disable
    stop-mode: sigterm-all
    stop-timeout: 5m
    plugs:
      - block-devices
      - hardware-observe
      - network
      - network-bind

  rgw:
    command: commands/rgw.start
    daemon: simple
    install-mode: disable
    plugs:
      - hardware-observe
      - network
      - network-bind

  # Commands
  ceph:
    command: commands/ceph
    plugs:
      - network
  "radosgw-admin":
    command: commands/radosgw-admin
    plugs:
      - network
  microceph:
    command: commands/microceph
    plugs:
      - network
  rbd:
    command: commands/rbd
    plugs:
      - network
  rados:
    command: commands/rados
    plugs:
      - network

parts:
  ceph:
    plugin: nil
    stage-packages:
      - ceph-common
      - ceph-mds
      - ceph-mgr
      - ceph-mgr-dashboard
      - ceph-mon
      - ceph-osd
      - radosgw
    organize:
      usr/bin/: bin/
      usr/sbin/: bin/
      usr/lib/: lib/
      usr/share/: share/
    prime:
      - bin/ceph
      - bin/ceph-authtool
      - bin/ceph-bluestore-tool
      - bin/ceph-mds
      - bin/ceph-mgr
      - bin/ceph-mon
      - bin/ceph-osd
      - bin/monmaptool
      - bin/rbd
      - bin/rados
      - bin/radosgw
      - bin/radosgw-admin
      - lib/*/ceph
      - lib/*/libaio.so*
      - lib/*/libasn1.so*
      - lib/*/libboost_context.so*
      - lib/*/libboost_filesystem.so*
      - lib/*/libboost_iostreams.so*
      - lib/*/libboost_program_options.so*
      - lib/*/libboost_python310.so*
      - lib/*/libboost_thread.so*
      - lib/*/libcephfs.so*
      - lib/*/libcephsqlite.so*
      - lib/*/libcurl-gnutls.so*
      - lib/*/libdaxctl.so*
      - lib/*/libfuse3.so*
      - lib/*/libibverbs.so*
      - lib/*/libicudata.so*
      - lib/*/libicuuc.so*
      - lib/*/liblber-2.5.so*
      - lib/*/libldap-2.5.so*
      - lib/*/liblua5.3.so*
      - lib/*/libndctl.so*
      - lib/*/libnghttp2.so*
      - lib/*/libnuma.so*
      - lib/*/liboath.so*
      - lib/*/libpmem.so*
      - lib/*/libpmemobj.so*
      - lib/*/libpsl.so*
      - lib/*/libpython3.10.so*
      - lib/*/librabbitmq.so*
      - lib/*/librados.so*
      - lib/*/libradosgw.so*
      - lib/*/libradosstriper.so.*
      - lib/*/librbd.so*
      - lib/*/librdmacm.so*
      - lib/*/libroken.so*
      - lib/*/librtmp.so*
      - lib/*/libsasl2.so*
      - lib/*/libsnappy.so*
      - lib/*/libwind.so*
      - lib/python3
      - lib/*/rados-classes
      - share/ceph

  deps:
    plugin: nil
    stage-packages:
      - uuid-runtime
    organize:
      usr/bin/: bin/
    prime:
      - bin/uuidgen

  dqlite:
    build-attributes: [core22-step-dependencies]
    after:
      - raft
    source: https://github.com/canonical/dqlite
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
    stage-packages:
      - libuv1
      - libsqlite3-0
    build-packages:
      - libuv1-dev
      - libsqlite3-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libdqlite*so*
      - lib/*/libuv*

  raft:
    build-attributes: [core22-step-dependencies]
    source: https://github.com/canonical/raft
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
    stage-packages:
      - libuv1
      - liblz4-1
    build-packages:
      - libuv1-dev
      - liblz4-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libraft*so*
      - lib/*/libuv.so*

  microceph:
    build-attributes: [core22-step-dependencies]
    source: microceph/
    after:
      - dqlite
    build-snaps:
      - go
    plugin: nil
    override-pull: |
      snapcraftctl pull
      set -ex

      # Download the dependencies
      go get -d -v ./...
    override-build: |
      set -ex

      # Setup build environment
      export CGO_CFLAGS="-I${SNAPCRAFT_STAGE}/include/ -I${SNAPCRAFT_STAGE}/usr/local/include/"
      export CGO_LDFLAGS="-L${SNAPCRAFT_STAGE}/lib/ -L${SNAPCRAFT_STAGE}/usr/local/lib/"
      export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"

      # Build the binaries
      go build -o "${SNAPCRAFT_PART_INSTALL}/bin/microceph" ./cmd/microceph
      go build -o "${SNAPCRAFT_PART_INSTALL}/bin/microcephd" -tags=libsqlite3 ./cmd/microcephd
    prime:
      - bin/microceph
      - bin/microcephd

  wrappers:
    plugin: dump
    source: snapcraft/
