package database

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/canonical/lxd/lxd/db/query"
	"github.com/canonical/lxd/shared/api"
	"github.com/canonical/microcluster/v2/cluster"
)

var _ = api.ServerEnvironment{}

var hostTagObjects = cluster.RegisterStmt(`
SELECT host_tags.id, core_cluster_members.name AS member, host_tags.key, host_tags.value
  FROM host_tags
  JOIN core_cluster_members ON host_tags.member_id = core_cluster_members.id
  ORDER BY core_cluster_members.id, host_tags.key
`)

var hostTagObjectsByMember = cluster.RegisterStmt(`
SELECT host_tags.id, core_cluster_members.name AS member, host_tags.key, host_tags.value
  FROM host_tags
  JOIN core_cluster_members ON host_tags.member_id = core_cluster_members.id
  WHERE ( member = ? )
  ORDER BY core_cluster_members.id, host_tags.key
`)

var hostTagObjectsByKey = cluster.RegisterStmt(`
SELECT host_tags.id, core_cluster_members.name AS member, host_tags.key, host_tags.value
  FROM host_tags
  JOIN core_cluster_members ON host_tags.member_id = core_cluster_members.id
  WHERE ( host_tags.key = ? )
  ORDER BY core_cluster_members.id, host_tags.key
`)

var hostTagObjectsByMemberAndKey = cluster.RegisterStmt(`
SELECT host_tags.id, core_cluster_members.name AS member, host_tags.key, host_tags.value
  FROM host_tags
  JOIN core_cluster_members ON host_tags.member_id = core_cluster_members.id
  WHERE ( member = ? AND host_tags.key = ? )
  ORDER BY core_cluster_members.id, host_tags.key
`)

var hostTagID = cluster.RegisterStmt(`
SELECT host_tags.id FROM host_tags
  JOIN core_cluster_members ON host_tags.member_id = core_cluster_members.id
  WHERE core_cluster_members.name = ? AND host_tags.key = ?
`)

var hostTagCreate = cluster.RegisterStmt(`
INSERT INTO host_tags (member_id, key, value)
  VALUES ((SELECT core_cluster_members.id FROM core_cluster_members WHERE core_cluster_members.name = ?), ?, ?)
`)

var hostTagDeleteByMember = cluster.RegisterStmt(`
DELETE FROM host_tags WHERE member_id = (SELECT core_cluster_members.id FROM core_cluster_members WHERE core_cluster_members.name = ?)
`)

var hostTagDeleteByMemberAndKey = cluster.RegisterStmt(`
DELETE FROM host_tags WHERE member_id = (SELECT core_cluster_members.id FROM core_cluster_members WHERE core_cluster_members.name = ?) AND key = ?
`)

var hostTagUpdate = cluster.RegisterStmt(`
UPDATE host_tags
  SET member_id = (SELECT core_cluster_members.id FROM core_cluster_members WHERE core_cluster_members.name = ?), key = ?, value = ?
 WHERE id = ?
`)

// hostTagColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the HostTag entity.
func hostTagColumns() string {
	return "hosts_tags.id, core_cluster_members.name AS member, hosts_tags.key, hosts_tags.value"
}

// getHostTags can be used to run handwritten sql.Stmts to return a slice of objects.
func getHostTags(ctx context.Context, stmt *sql.Stmt, args ...any) ([]HostTag, error) {
	objects := make([]HostTag, 0)

	dest := func(scan func(dest ...any) error) error {
		h := HostTag{}
		err := scan(&h.ID, &h.Member, &h.Key, &h.Value)
		if err != nil {
			return err
		}

		objects = append(objects, h)

		return nil
	}

	err := query.SelectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"hosts_tags\" table: %w", err)
	}

	return objects, nil
}

// getHostTagsRaw can be used to run handwritten query strings to return a slice of objects.
func getHostTagsRaw(ctx context.Context, tx *sql.Tx, sql string, args ...any) ([]HostTag, error) {
	objects := make([]HostTag, 0)

	dest := func(scan func(dest ...any) error) error {
		h := HostTag{}
		err := scan(&h.ID, &h.Member, &h.Key, &h.Value)
		if err != nil {
			return err
		}

		objects = append(objects, h)

		return nil
	}

	err := query.Scan(ctx, tx, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"hosts_tags\" table: %w", err)
	}

	return objects, nil
}

// GetHostTags returns all available host_tags.
// generator: host_tag GetMany
func GetHostTags(ctx context.Context, tx *sql.Tx, filters ...HostTagFilter) ([]HostTag, error) {
	var err error

	// Result slice.
	objects := make([]HostTag, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = cluster.Stmt(tx, hostTagObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"hostTagObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.Member != nil && filter.Key != nil {
			args = append(args, []any{filter.Member, filter.Key}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, hostTagObjectsByMemberAndKey)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"hostTagObjectsByMemberAndKey\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(hostTagObjectsByMemberAndKey)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"hostTagObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Member != nil && filter.Key == nil {
			args = append(args, []any{filter.Member}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, hostTagObjectsByMember)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"hostTagObjectsByMember\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(hostTagObjectsByMember)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"hostTagObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Key != nil && filter.Member == nil {
			args = append(args, []any{filter.Key}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, hostTagObjectsByKey)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"hostTagObjectsByKey\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(hostTagObjectsByKey)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"hostTagObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Member == nil && filter.Key == nil {
			return nil, fmt.Errorf("Cannot filter on empty HostTagFilter")
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getHostTags(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getHostTagsRaw(ctx, tx, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"hosts_tags\" table: %w", err)
	}

	return objects, nil
}

// GetHostTag returns the host_tag with the given key.
// generator: host_tag GetOne
func GetHostTag(ctx context.Context, tx *sql.Tx, member string, key string) (*HostTag, error) {
	filter := HostTagFilter{}
	filter.Member = &member
	filter.Key = &key

	objects, err := GetHostTags(ctx, tx, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"hosts_tags\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, api.StatusErrorf(http.StatusNotFound, "HostTag not found")
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"hosts_tags\" entry matches")
	}
}

// GetHostTagID return the ID of the host_tag with the given key.
// generator: host_tag ID
func GetHostTagID(ctx context.Context, tx *sql.Tx, member string, key string) (int64, error) {
	stmt, err := cluster.Stmt(tx, hostTagID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"hostTagID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, member, key)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, api.StatusErrorf(http.StatusNotFound, "HostTag not found")
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"hosts_tags\" ID: %w", err)
	}

	return id, nil
}

// HostTagExists checks if a host_tag with the given key exists.
// generator: host_tag Exists
func HostTagExists(ctx context.Context, tx *sql.Tx, member string, key string) (bool, error) {
	_, err := GetHostTagID(ctx, tx, member, key)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}

		return false, err
	}

	return true, nil
}

// CreateHostTag adds a new host_tag to the database.
// generator: host_tag Create
func CreateHostTag(ctx context.Context, tx *sql.Tx, object HostTag) (int64, error) {
	// Check if a host_tag with the same key exists.
	exists, err := HostTagExists(ctx, tx, object.Member, object.Key)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"hosts_tags\" entry already exists")
	}

	args := make([]any, 3)

	// Populate the statement arguments.
	args[0] = object.Member
	args[1] = object.Key
	args[2] = object.Value

	// Prepared statement to use.
	stmt, err := cluster.Stmt(tx, hostTagCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"hostTagCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"hosts_tags\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"hosts_tags\" entry ID: %w", err)
	}

	return id, nil
}

// DeleteHostTag deletes the host_tag matching the given key parameters.
// generator: host_tag DeleteOne-by-Member-and-Key
func DeleteHostTag(ctx context.Context, tx *sql.Tx, member string, key string) error {
	stmt, err := cluster.Stmt(tx, hostTagDeleteByMemberAndKey)
	if err != nil {
		return fmt.Errorf("Failed to get \"hostTagDeleteByMemberAndKey\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(member, key)
	if err != nil {
		return fmt.Errorf("Delete \"hosts_tags\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return api.StatusErrorf(http.StatusNotFound, "HostTag not found")
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d HostTag rows instead of 1", n)
	}

	return nil
}

// DeleteHostTags deletes the host_tag matching the given key parameters.
// generator: host_tag DeleteMany-by-Member
func DeleteHostTags(ctx context.Context, tx *sql.Tx, member string) error {
	stmt, err := cluster.Stmt(tx, hostTagDeleteByMember)
	if err != nil {
		return fmt.Errorf("Failed to get \"hostTagDeleteByMember\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(member)
	if err != nil {
		return fmt.Errorf("Delete \"hosts_tags\": %w", err)
	}

	_, err = result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	return nil
}

// UpdateHostTag updates the host_tag matching the given key parameters.
// generator: host_tag Update
func UpdateHostTag(ctx context.Context, tx *sql.Tx, member string, key string, object HostTag) error {
	id, err := GetHostTagID(ctx, tx, member, key)
	if err != nil {
		return err
	}

	stmt, err := cluster.Stmt(tx, hostTagUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"hostTagUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.Member, object.Key, object.Value, id)
	if err != nil {
		return fmt.Errorf("Update \"hosts_tags\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}
