"""Unit tests for the pure helpers in the MicroCeph Robot Framework harness.

These cover the @staticmethod parsers and the generic _poll_until poller on the
microceph_harness class, plus the standalone snap_services / cephfs_replication
helpers. The helpers are pure (no self, no BuiltIn), so importing the module and
calling them needs no running Robot context -- only that robotframework is
importable (microceph_harness imports robot.api at module top).

Run with pytest:
    pytest tests/robot/resources/test_harness_helpers.py
"""

import json

import placement_status
from microceph_harness import microceph_harness as H
from cluster_ops import parse_migration_status
from snap_services import enabled_active_services
from cephfs_replication import cephfs_replication_list_has_volume, verify_cephfs_list_entry_types
from rbd_replication import (
    rbd_mirror_health,
    rbd_primary_image_count,
    rbd_synced_image_count,
)
from rgw_replication import parse_rgw_replication_status, rgw_data_sync_states
from streaming_process import run_streaming_process


# ---------------------------------------------------------------------------
# _safe_int
# ---------------------------------------------------------------------------

def test_safe_int_plain_digits():
    assert H._safe_int("3") == 3


def test_safe_int_strips_whitespace():
    assert H._safe_int(" 5 ") == 5


def test_safe_int_empty_is_zero():
    assert H._safe_int("") == 0


def test_safe_int_non_numeric_is_zero():
    assert H._safe_int("x") == 0


def test_safe_int_negative_is_zero():
    # isdigit() is False for a leading '-', so this falls back to 0.
    assert H._safe_int("-1") == 0


# ---------------------------------------------------------------------------
# _ceph_conf_value
# ---------------------------------------------------------------------------

CEPH_CONF_SAMPLE = """# Generated by MicroCeph, DO NOT EDIT.
[global]
run dir = /var/snap/microceph/current/run
fsid = aabbccdd-1234
mon host = 10.20.0.10
public_network = 10.10.0.1/24,10.20.0.1/24
ms bind ipv4 = true
ms bind ipv6 = false
"""


def test_ceph_conf_value_multi_subnet_public_network():
    # The comma-delimited list is returned verbatim (the multi-subnet invariant).
    assert (
        H._ceph_conf_value(CEPH_CONF_SAMPLE, "public_network")
        == "10.10.0.1/24,10.20.0.1/24"
    )


def test_ceph_conf_value_key_with_space():
    assert H._ceph_conf_value(CEPH_CONF_SAMPLE, "mon host") == "10.20.0.10"


def test_ceph_conf_value_absent_key_is_empty():
    assert H._ceph_conf_value(CEPH_CONF_SAMPLE, "cluster_network") == ""


def test_ceph_conf_value_skips_section_headers_and_blanks():
    assert H._ceph_conf_value("[global]\n\nfsid = x\n", "fsid") == "x"


# ---------------------------------------------------------------------------
# _last_eth_interface
# ---------------------------------------------------------------------------

IP_A_SAMPLE = """1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0@if5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:aa:bb:cc brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.10.0.10/24 scope global eth0
3: eth2@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:dd:ee:ff brd ff:ff:ff:ff:ff:ff link-netnsid 0
4: eth3@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:11:22:33 brd ff:ff:ff:ff:ff:ff link-netnsid 0
"""


def test_last_eth_interface_picks_highest_indexed():
    # The most recently attached NIC has the highest ifindex, so it is last.
    assert H._last_eth_interface(IP_A_SAMPLE) == "eth3"


def test_last_eth_interface_strips_veth_peer_and_skips_sublines():
    # Only header lines match; the @peer suffix is dropped and inet sub-lines ignored.
    assert H._last_eth_interface("2: eth0@if5: <UP>\n    inet 10.0.0.1/24\n") == "eth0"


def test_last_eth_interface_handles_no_peer_suffix():
    assert H._last_eth_interface("5: eth7: <UP> mtu 1500\n") == "eth7"


def test_last_eth_interface_none_present_returns_empty():
    assert H._last_eth_interface("1: lo: <LOOPBACK>\n2: enp5s0: <UP>\n") == ""


# ---------------------------------------------------------------------------
# _coerce_xtrace
# ---------------------------------------------------------------------------

def test_coerce_xtrace_bool_false():
    assert H._coerce_xtrace(False) is False


def test_coerce_xtrace_string_true():
    assert H._coerce_xtrace("True") is True


def test_coerce_xtrace_yes():
    assert H._coerce_xtrace("yes") is True


def test_coerce_xtrace_one():
    assert H._coerce_xtrace("1") is True


def test_coerce_xtrace_off():
    assert H._coerce_xtrace("off") is False


def test_coerce_xtrace_empty():
    assert H._coerce_xtrace("") is False


def test_coerce_xtrace_bool_true():
    assert H._coerce_xtrace(True) is True


# ---------------------------------------------------------------------------
# _ceph_osd_counts
# ---------------------------------------------------------------------------

def test_ceph_osd_counts_valid():
    payload = json.dumps({"osdmap": {"num_up_osds": 3, "num_in_osds": 2}})
    assert H._ceph_osd_counts(payload) == (3, 2)


def test_ceph_osd_counts_missing_osdmap():
    assert H._ceph_osd_counts(json.dumps({})) == (0, 0)


def test_ceph_osd_counts_empty_string():
    assert H._ceph_osd_counts("") == (0, 0)


def test_ceph_osd_counts_garbage():
    assert H._ceph_osd_counts("not json at all") == (0, 0)


# ---------------------------------------------------------------------------
# _rgw_daemon_count
# ---------------------------------------------------------------------------

def test_rgw_daemon_count_present():
    text = (
        "  services:\n"
        "    mon: 1 daemons, quorum node-wrk0\n"
        "    rgw: 2 daemons active (1 hosts, 1 zones)\n"
    )
    assert H._rgw_daemon_count(text) == 2


def test_rgw_daemon_count_no_rgw_line():
    text = (
        "  services:\n"
        "    mon: 1 daemons, quorum node-wrk0\n"
        "    osd: 3 osds: 3 up, 3 in\n"
    )
    assert H._rgw_daemon_count(text) == 0


def test_rgw_daemon_count_empty_string():
    assert H._rgw_daemon_count("") == 0


def test_rgw_daemon_count_rgw_line_no_digit_match():
    # An "rgw:" line with no "<n> daemon" match returns 0 rather than raising.
    assert H._rgw_daemon_count("    rgw: active\n") == 0


# ---------------------------------------------------------------------------
# _cephfs_snaps_synced_total
# ---------------------------------------------------------------------------

def test_cephfs_snaps_synced_total_dict_shape_real_api():
    # Real microceph output: peers AND mirror_status are JSON OBJECTS (Go maps,
    # api/types/replication_cephfs.go:115,121), keyed by uuid / dir-path. Each is
    # iterated by VALUE, matching the pre-refactor jq '.peers[].mirror_status | .[]'.
    payload = json.dumps(
        {
            "volume": "vol1",
            "mirror_path_count": 2,
            "peers": {
                "uuid-1": {"name": "siteb", "mirror_status": {"/d1": {"snaps_synced": 5}}},
                "uuid-2": {"name": "sitec", "mirror_status": {"/d2": {"snaps_synced": 3}}},
            },
        }
    )
    assert H._cephfs_snaps_synced_total(payload) == 8


def test_cephfs_snaps_synced_total_list_fallback():
    # List-shaped peers/mirror_status are still accepted for robustness.
    payload = json.dumps(
        {
            "peers": [
                {"mirror_status": [{"snaps_synced": 2}, {"snaps_synced": 3}]},
                {"mirror_status": [{"snaps_synced": 5}]},
            ]
        }
    )
    assert H._cephfs_snaps_synced_total(payload) == 10


def test_cephfs_snaps_synced_total_mirror_status_dict_value_iterated():
    payload = json.dumps(
        {"peers": {"u": {"mirror_status": {"a": {"snaps_synced": 4}, "b": {"snaps_synced": 6}}}}}
    )
    assert H._cephfs_snaps_synced_total(payload) == 10


def test_cephfs_snaps_synced_total_missing_field_defaults_zero():
    payload = json.dumps({"peers": {"u": {"mirror_status": {"a": {}, "b": {"snaps_synced": 7}}}}})
    assert H._cephfs_snaps_synced_total(payload) == 7


def test_cephfs_snaps_synced_total_null_peers_is_zero():
    # A nil Go map marshals to JSON null; jq's // 0 coerced it, so must we.
    assert H._cephfs_snaps_synced_total(json.dumps({"peers": None})) == 0


def test_cephfs_snaps_synced_total_null_mirror_status_is_zero():
    payload = json.dumps({"peers": {"u": {"mirror_status": None}}})
    assert H._cephfs_snaps_synced_total(payload) == 0


def test_cephfs_snaps_synced_total_null_snaps_synced_is_zero():
    payload = json.dumps({"peers": {"u": {"mirror_status": {"a": {"snaps_synced": None}}}}})
    assert H._cephfs_snaps_synced_total(payload) == 0


def test_cephfs_snaps_synced_total_empty_string():
    assert H._cephfs_snaps_synced_total("") == 0


def test_cephfs_snaps_synced_total_garbage():
    assert H._cephfs_snaps_synced_total("garbage") == 0


# ---------------------------------------------------------------------------
# _parse_network_cidr
# ---------------------------------------------------------------------------

def test_parse_network_cidr_public_row():
    # Mirrors `lxc network list --format=csv` columns
    # (NAME,TYPE,MANAGED,IPV4,...); cut -d, -f4 == the IPv4 CIDR at index 3.
    csv_text = (
        "lxdbr0,bridge,YES,10.123.45.1/24,fd42::/64,,1,CREATED\n"
        "public,bridge,YES,10.0.0.1/24,,,0,CREATED\n"
        "internal,bridge,YES,10.1.0.1/24,,,0,CREATED\n"
    )
    assert H._parse_network_cidr(csv_text, "public") == "10.0.0.1/24"


def test_parse_network_cidr_internal_row():
    csv_text = (
        "public,bridge,YES,10.0.0.1/24,,,0,CREATED\n"
        "internal,bridge,YES,10.1.0.1/24,,,0,CREATED\n"
    )
    assert H._parse_network_cidr(csv_text, "internal") == "10.1.0.1/24"


def test_parse_network_cidr_no_match_returns_empty():
    csv_text = "public,bridge,YES,10.0.0.1/24,,,0,CREATED\n"
    assert H._parse_network_cidr(csv_text, "internal") == ""


def test_parse_network_cidr_empty_input_returns_empty():
    assert H._parse_network_cidr("", "public") == ""


def test_parse_network_cidr_returns_first_match():
    csv_text = (
        "public,bridge,YES,10.0.0.1/24,,,0,CREATED\n"
        "public,bridge,YES,10.9.9.1/24,,,0,CREATED\n"
    )
    assert H._parse_network_cidr(csv_text, "public") == "10.0.0.1/24"


def test_parse_network_cidr_short_row_returns_empty():
    # A matching line with fewer than 4 comma fields yields "".
    assert H._parse_network_cidr("public,bridge,YES\n", "public") == ""


# ---------------------------------------------------------------------------
# _host_address
# ---------------------------------------------------------------------------

def test_host_address_standard_24():
    # The ".10" head host the suite assigns on a /24 gateway CIDR.
    assert H._host_address("10.0.0.1/24", 10) == "10.0.0.10"


def test_host_address_gateway_host_part_ignored():
    # Arithmetic is on the network address, so the gateway's host part is
    # irrelevant
    assert H._host_address("10.0.0.249/24", 10) == "10.0.0.10"


def test_host_address_16_prefix():
    # strict=False masks the host bits before computing the network address.
    assert H._host_address("10.1.0.1/16", 10) == "10.1.0.10"


# ---------------------------------------------------------------------------
# _count_configured_disks
# ---------------------------------------------------------------------------

def test_count_configured_disks_single_substring():
    payload = json.dumps(
        {
            "ConfiguredDisks": [
                {"path": "/dev/vgtst/lvtest"},
                {"path": "/dev/sdc"},
            ]
        }
    )
    assert H._count_configured_disks(payload, "/dev/vgtst/lvtest") == 1


def test_count_configured_disks_multiple_substrings():
    payload = json.dumps(
        {
            "ConfiguredDisks": [
                {"path": "/dev/sdia"},
                {"path": "/dev/sdib"},
                {"path": "/dev/sdc"},
            ]
        }
    )
    assert H._count_configured_disks(payload, "/dev/sdia", "/dev/sdib") == 2


def test_count_configured_disks_no_match_is_zero():
    payload = json.dumps({"ConfiguredDisks": [{"path": "/dev/sdc"}]})
    assert H._count_configured_disks(payload, "/dev/sdia") == 0


def test_count_configured_disks_missing_key_is_zero():
    assert H._count_configured_disks(json.dumps({}), "/dev/sdia") == 0


def test_count_configured_disks_garbage_is_zero():
    assert H._count_configured_disks("not json at all", "/dev/sdia") == 0


def test_count_configured_disks_empty_string_is_zero():
    assert H._count_configured_disks("", "/dev/sdia") == 0


def test_count_configured_disks_entry_without_path_is_skipped():
    payload = json.dumps({"ConfiguredDisks": [{}, {"path": "/dev/sdia"}]})
    assert H._count_configured_disks(payload, "/dev/sdia") == 1


# ---------------------------------------------------------------------------
# _poll_until
# ---------------------------------------------------------------------------

def test_poll_until_returns_when_predicate_true_on_third_call():
    calls = []

    def predicate():
        calls.append(1)
        return len(calls) == 3

    H._poll_until(predicate, attempts=10, interval=0, fail_msg="boom")
    assert len(calls) == 3


def test_poll_until_raises_after_attempts_when_always_false():
    calls = []

    def predicate():
        calls.append(1)
        return False

    raised = False
    try:
        H._poll_until(predicate, attempts=4, interval=0, fail_msg="never happened")
    except AssertionError as exc:
        raised = True
        assert str(exc) == "never happened"
    assert raised
    assert len(calls) == 4


def test_poll_until_invokes_between_between_probes():
    between_calls = []

    def predicate():
        return False

    def between():
        between_calls.append(1)

    try:
        H._poll_until(
            predicate,
            attempts=3,
            interval=0,
            fail_msg="x",
            between=between,
        )
    except AssertionError:
        pass
    # between runs after each failed probe -> once per attempt.
    assert len(between_calls) == 3


def test_poll_until_invokes_on_fail_on_exhaustion():
    on_fail_calls = []

    def predicate():
        return False

    def on_fail():
        on_fail_calls.append(1)

    try:
        H._poll_until(
            predicate,
            attempts=2,
            interval=0,
            fail_msg="x",
            on_fail=on_fail,
        )
    except AssertionError:
        pass
    assert len(on_fail_calls) == 1


def test_poll_until_no_raise_when_raise_on_timeout_false():
    def predicate():
        return False

    # Should simply return without raising.
    H._poll_until(
        predicate,
        attempts=2,
        interval=0,
        fail_msg="should not be raised",
        raise_on_timeout=False,
    )


def test_poll_until_accepts_string_interval():
    # Production callers pass Robot time strings ('3s'/'15s'/'5s'); '0s' exercises the
    # timestr_to_secs branch without actually sleeping.
    calls = []

    def predicate():
        calls.append(1)
        return False

    try:
        H._poll_until(predicate, attempts=3, interval="0s", fail_msg="x")
    except AssertionError:
        pass
    assert len(calls) == 3


def test_poll_until_between_not_called_on_success():
    between_calls = []

    def predicate():
        return True

    def between():
        between_calls.append(1)

    H._poll_until(predicate, attempts=3, interval=0, fail_msg="x", between=between)
    assert between_calls == []


# ---------------------------------------------------------------------------
# enabled_active_services (snap_services.py)
# ---------------------------------------------------------------------------

def test_enabled_active_services_filters_enabled_and_active():
    output = (
        "Service                 Startup   Current   Notes\n"
        "microceph.daemon        enabled   active    -\n"
        "microceph.mds           enabled   inactive  -\n"
        "microceph.mgr           disabled  active    -\n"
        "microceph.osd           enabled   active    -\n"
    )
    assert enabled_active_services(output) == ["microceph.daemon", "microceph.osd"]


def test_enabled_active_services_empty_string():
    assert enabled_active_services("") == []


def test_enabled_active_services_header_only():
    assert enabled_active_services("Service  Startup  Current  Notes\n") == []


# ---------------------------------------------------------------------------
# cephfs_replication_list_has_volume (cephfs_replication.py)
# ---------------------------------------------------------------------------

def test_cephfs_replication_list_has_volume_present_nonempty():
    payload = json.dumps({"myfs": [{"resource_path": "/a", "resource_type": "directory"}]})
    assert cephfs_replication_list_has_volume(payload, "myfs") is True


def test_cephfs_replication_list_has_volume_absent_key():
    payload = json.dumps({"otherfs": [{"resource_path": "/a"}]})
    assert cephfs_replication_list_has_volume(payload, "myfs") is False


def test_cephfs_replication_list_has_volume_empty_object():
    assert cephfs_replication_list_has_volume(json.dumps({}), "myfs") is False


def test_cephfs_replication_list_has_volume_empty_list_value():
    # Key present but maps to an empty list -> not synced yet -> False (bool([]) path).
    assert cephfs_replication_list_has_volume(json.dumps({"myfs": []}), "myfs") is False


def test_cephfs_replication_list_has_volume_bad_json():
    assert cephfs_replication_list_has_volume("not json", "myfs") is False


# ---------------------------------------------------------------------------
# verify_cephfs_list_entry_types (cephfs_replication.py) -- imported per spec
# ---------------------------------------------------------------------------

def test_verify_cephfs_list_entry_types_ok():
    payload = json.dumps(
        {
            "vol": [
                {"resource_path": "/volumes/sub", "resource_type": "subvolume"},
                {"resource_path": "/data", "resource_type": "directory"},
            ]
        }
    )
    items = verify_cephfs_list_entry_types(payload, "vol")
    assert len(items) == 2


def test_verify_cephfs_list_entry_types_mismatch_raises():
    payload = json.dumps(
        {"vol": [{"resource_path": "/volumes/sub", "resource_type": "directory"}]}
    )
    raised = False
    try:
        verify_cephfs_list_entry_types(payload, "vol")
    except AssertionError:
        raised = True
    assert raised


def test_verify_cephfs_list_entry_types_absent_volume_raises():
    # Volume key not present at all -> AssertionError (was an empty-jq -> empty-list case).
    payload = json.dumps({"other": [{"resource_path": "/d", "resource_type": "directory"}]})
    raised = False
    try:
        verify_cephfs_list_entry_types(payload, "vol")
    except AssertionError:
        raised = True
    assert raised


def test_verify_cephfs_list_entry_types_empty_volume_raises():
    # Volume present but maps to no entries -> AssertionError.
    raised = False
    try:
        verify_cephfs_list_entry_types(json.dumps({"vol": []}), "vol")
    except AssertionError:
        raised = True
    assert raised


def test_verify_cephfs_list_entry_types_bad_json_raises():
    # Malformed JSON now raises AssertionError rather than letting JSONDecodeError escape.
    raised = False
    try:
        verify_cephfs_list_entry_types("not json", "vol")
    except AssertionError:
        raised = True
    assert raised


# ---------------------------------------------------------------------------
# _rbd_synced_image_count
# ---------------------------------------------------------------------------

def test_rbd_synced_image_count_sums_images():
    payload = json.dumps(
        [
            {"Images": [{"name": "img1"}, {"name": "img2"}]},
            {"Images": [{"name": "img3"}]},
        ]
    )
    assert rbd_synced_image_count(payload) == 3


def test_rbd_synced_image_count_entry_without_images_is_zero():
    payload = json.dumps([{}, {"Images": [{"name": "img1"}]}])
    assert rbd_synced_image_count(payload) == 1


def test_rbd_synced_image_count_empty_list_is_zero():
    assert rbd_synced_image_count("[]") == 0


def test_rbd_synced_image_count_garbage_is_zero():
    assert rbd_synced_image_count("not json at all") == 0


def test_rbd_synced_image_count_empty_string_is_zero():
    assert rbd_synced_image_count("") == 0


def test_rbd_synced_image_count_null_images_is_zero():
    # A null Images list (jq //-equivalent) must not raise; the Go marshaller emits
    # [] today but the helper guards null for parity with jq.
    assert rbd_synced_image_count(json.dumps([{"Images": None}])) == 0


# ---------------------------------------------------------------------------
# _rbd_primary_image_count
# ---------------------------------------------------------------------------

def test_rbd_primary_image_count_counts_primary():
    payload = json.dumps(
        [
            {"Images": [{"is_primary": True}, {"is_primary": False}]},
            {"Images": [{"is_primary": True}]},
        ]
    )
    assert rbd_primary_image_count(payload) == 2


def test_rbd_primary_image_count_none_primary_is_zero():
    payload = json.dumps([{"Images": [{"is_primary": False}, {"is_primary": False}]}])
    assert rbd_primary_image_count(payload) == 0


def test_rbd_primary_image_count_missing_flag_is_zero():
    payload = json.dumps([{"Images": [{"name": "img1"}]}])
    assert rbd_primary_image_count(payload) == 0


def test_rbd_primary_image_count_garbage_is_zero():
    assert rbd_primary_image_count("not json at all") == 0


def test_rbd_primary_image_count_empty_string_is_zero():
    assert rbd_primary_image_count("") == 0


def test_rbd_primary_image_count_null_images_is_zero():
    assert rbd_primary_image_count(json.dumps([{"Images": None}])) == 0


# ---------------------------------------------------------------------------
# _rbd_mirror_health
# ---------------------------------------------------------------------------

def test_rbd_mirror_health_ok():
    text = (
        "health: OK\n"
        "daemon health: OK\n"
        "image health: OK\n"
    )
    assert rbd_mirror_health(text) == "OK"


def test_rbd_mirror_health_first_line_wins():
    text = "health: WARNING\nhealth: OK\n"
    assert rbd_mirror_health(text) == "WARNING"


def test_rbd_mirror_health_no_health_line_is_unknown():
    text = "daemon health: OK\nsome other line\n"
    assert rbd_mirror_health(text) == "UNKNOWN"


def test_rbd_mirror_health_empty_value_is_unknown():
    assert rbd_mirror_health("health: \n") == "UNKNOWN"


def test_rbd_mirror_health_empty_text_is_unknown():
    assert rbd_mirror_health("") == "UNKNOWN"


# ---------------------------------------------------------------------------
# _remote_list_has
# ---------------------------------------------------------------------------

def test_remote_list_has_matching_name():
    payload = json.dumps([{"name": "siteb", "local_name": "sitea"}])
    assert H._remote_list_has(payload, "name", "siteb") is True


def test_remote_list_has_matching_local_name():
    payload = json.dumps([{"name": "siteb", "local_name": "sitea"}])
    assert H._remote_list_has(payload, "local_name", "sitea") is True


def test_remote_list_has_no_match():
    payload = json.dumps([{"name": "siteb", "local_name": "sitea"}])
    assert H._remote_list_has(payload, "name", "sitec") is False


def test_remote_list_has_empty_list():
    assert H._remote_list_has("[]", "name", "siteb") is False


def test_remote_list_has_garbage_is_false():
    assert H._remote_list_has("not json", "name", "siteb") is False


def test_remote_list_has_null_is_false():
    assert H._remote_list_has("null", "name", "siteb") is False


# ---------------------------------------------------------------------------
# run_streaming_process (streaming_process.py)
#
# Exercised with trivial local subprocesses -- no LXD needed. Covers the
# [rc, combined_output] return shape, xtrace prefixing, and the process-group
# timeout kill.
# ---------------------------------------------------------------------------

def test_run_streaming_process_echo_returns_rc_and_output():
    rc, out = run_streaming_process("echo hello-stream")
    assert rc == 0
    assert "hello-stream" in out


def test_run_streaming_process_nonzero_rc():
    rc, out = run_streaming_process("false")
    assert rc != 0


def test_run_streaming_process_xtrace_traces_script(tmp_path):
    # xtrace prepends `bash -x`, which traces the script body to stderr (merged into
    # stdout); the '+ echo ...' trace marker proves the prefix was applied.
    script = tmp_path / "traced.sh"
    script.write_text("echo traced-content\n")
    rc, out = run_streaming_process(str(script), xtrace=True)
    assert rc == 0
    assert "traced-content" in out
    assert "+ echo traced-content" in out


def test_run_streaming_process_timeout_kills_process_group():
    raised = False
    try:
        # The shell one-liner spawns a grandchild sleep; the process-group kill must
        # reap it so the call returns promptly instead of blocking on the open pipe.
        run_streaming_process("sleep 60", timeout=1)
    except RuntimeError as exc:
        raised = True
        assert "timed out" in str(exc)
    assert raised


def test_run_streaming_process_argv_list_runs_without_shell():
    # The argv-list form runs with shell=False; the components reach the program
    # verbatim with no shell word-splitting or metacharacter interpretation.
    rc, out = run_streaming_process(["printf", "%s", "hello-argv"])
    assert rc == 0
    assert "hello-argv" in out


# ---------------------------------------------------------------------------
# parse_migration_status (cluster_ops.py)
#
# Pure replacement for the `microceph status | grep -F -A 1 <node> | grep -qE
# '^  Services: ...$'` decision the service-migration test used. Two leading
# spaces and the exact service list are load-bearing -- the tests pin both.
# ---------------------------------------------------------------------------

_MIGRATED_STATUS = (
    "MicroCeph deployment summary:\n"
    "- node-wrk1 (10.0.0.11)\n"
    "  Services: osd\n"
    "  Disks: 1\n"
    "- node-wrk3 (10.0.0.13)\n"
    "  Services: mds, mgr, mon\n"
    "  Disks: 0\n"
)


def test_parse_migration_status_both_migrated():
    assert parse_migration_status(_MIGRATED_STATUS, "node-wrk1", "node-wrk3") == (True, True)


def test_parse_migration_status_neither_migrated():
    # Pre-migration: src still has everything, dst has only osd.
    text = (
        "- node-wrk1 (10.0.0.11)\n"
        "  Services: mds, mgr, mon, osd\n"
        "- node-wrk3 (10.0.0.13)\n"
        "  Services: osd\n"
    )
    assert parse_migration_status(text, "node-wrk1", "node-wrk3") == (False, False)


def test_parse_migration_status_partial():
    # src reduced to osd-only but dst not yet mds,mgr,mon -> (True, False).
    text = "- node-wrk1\n  Services: osd\n- node-wrk3\n  Services: osd\n"
    assert parse_migration_status(text, "node-wrk1", "node-wrk3") == (True, False)


def test_parse_migration_status_requires_exact_services():
    # An osd-only anchor must not match a line that lists extra services.
    text = "- node-wrk1\n  Services: mds, osd\n"
    src_ok, _ = parse_migration_status(text, "node-wrk1", "node-wrk9")
    assert src_ok is False


def test_parse_migration_status_requires_two_space_indent():
    # The original regex anchors exactly two leading spaces; other indents must not match.
    text = "- node-wrk1\n    Services: osd\n"  # four spaces
    src_ok, _ = parse_migration_status(text, "node-wrk1", "node-wrk9")
    assert src_ok is False


def test_parse_migration_status_absent_node_is_false():
    src_ok, dst_ok = parse_migration_status(_MIGRATED_STATUS, "node-wrk7", "node-wrk8")
    assert (src_ok, dst_ok) == (False, False)


# ---------------------------------------------------------------------------
# placement_status
# ---------------------------------------------------------------------------

_SYNC_PLACEMENT_RESPONSE = json.dumps({
    "type": "sync",
    "status": "Success",
    "status_code": 200,
    "metadata": {
        "active": True,
        "observed": None,
        "bootstrap_state": "not_bootstrapped",
    },
})

_ERROR_RESPONSE = json.dumps({
    "type": "error",
    "error_code": 400,
    "error": "keep-one invariant: refused to remove last mon on node-a",
})


def test_response_code_sync_success():
    assert placement_status.response_code(_SYNC_PLACEMENT_RESPONSE) == 200


def test_response_code_error_body():
    assert placement_status.response_code(_ERROR_RESPONSE) == 400


def test_response_code_garbage_is_zero():
    # Fail closed: comparisons against 200 must fail on unparseable bodies.
    assert placement_status.response_code("curl: (7) connection refused") == 0
    assert placement_status.response_code("") == 0
    assert placement_status.response_code(None) == 0


def test_response_code_non_dict_json_is_zero():
    assert placement_status.response_code("[1, 2, 3]") == 0


def test_bootstrap_state_from_metadata():
    assert placement_status.bootstrap_state(_SYNC_PLACEMENT_RESPONSE) == "not_bootstrapped"


def test_bootstrap_state_absent_is_empty():
    assert placement_status.bootstrap_state(_ERROR_RESPONSE) == ""
    assert placement_status.bootstrap_state("garbage") == ""


def test_placement_active_flag():
    assert placement_status.placement_active(_SYNC_PLACEMENT_RESPONSE) is True
    inactive = json.dumps({"status_code": 200, "metadata": {"active": False}})
    assert placement_status.placement_active(inactive) is False
    assert placement_status.placement_active("garbage") is False


def test_supported_capabilities_list():
    raw = json.dumps({
        "status_code": 200,
        "metadata": {"supported": ["deferred-ceph-bootstrap", "ceph-only-bootstrap"]},
    })
    assert placement_status.supported_capabilities(raw) == [
        "deferred-ceph-bootstrap",
        "ceph-only-bootstrap",
    ]


def test_supported_capabilities_malformed_is_empty():
    assert placement_status.supported_capabilities("garbage") == []
    non_list = json.dumps({"status_code": 200, "metadata": {"supported": "nope"}})
    assert placement_status.supported_capabilities(non_list) == []


def test_mon_count_prefers_monmap_num_mons():
    raw = json.dumps({"monmap": {"num_mons": 3}, "quorum_names": ["a", "b"]})
    assert placement_status.mon_count(raw) == 3


def test_mon_count_falls_back_to_quorum_names():
    raw = json.dumps({"quorum_names": ["a", "b"]})
    assert placement_status.mon_count(raw) == 2


def test_mon_count_garbage_is_zero():
    # Poll loops treat an unreachable/unready cluster as zero mons.
    assert placement_status.mon_count("Error connecting to cluster") == 0
    assert placement_status.mon_count("") == 0
    assert placement_status.mon_count("{}") == 0


def test_mon_quorum_names_prefers_explicit_names():
    raw = json.dumps(
        {
            "quorum_names": ["node-a", "node-b"],
            "quorum": [1],
            "monmap": {"mons": [{"rank": 1, "name": "wrong-fallback"}]},
        }
    )
    assert placement_status.mon_quorum_names(raw) == ["node-a", "node-b"]


def test_mon_quorum_names_maps_numeric_ranks_through_monmap():
    raw = json.dumps(
        {
            "quorum": [2, 0],
            "monmap": {
                "mons": [
                    {"rank": 0, "name": "node-a"},
                    {"rank": 1, "name": "node-b"},
                    {"rank": 2, "name": "node-c"},
                ]
            },
        }
    )
    assert placement_status.mon_quorum_names(raw) == ["node-c", "node-a"]


def test_mon_quorum_names_malformed_fails_closed():
    malformed = [
        "bad",
        "[]",
        "{}",
        json.dumps({"quorum": [0]}),
        json.dumps({"quorum": [0], "monmap": {"mons": []}}),
        json.dumps(
            {
                "quorum": [1],
                "monmap": {"mons": [{"rank": 0, "name": "node-a"}]},
            }
        ),
        json.dumps({"quorum_names": ["node-a", 1]}),
        json.dumps(
            {
                "quorum_names": None,
                "quorum": [0],
                "monmap": {"mons": [{"rank": 0, "name": "node-a"}]},
            }
        ),
    ]
    for raw in malformed:
        assert placement_status.mon_quorum_names(raw) == []


def test_control_service_presence_requires_each_explicit_service():
    mon = json.dumps({"quorum_names": ["node-a", "node-b"]})
    mgr = json.dumps([{"name": "node-a"}, {"name": "node-b"}])
    mds = json.dumps(
        {
            "fsmap": {
                "standbys": [{"name": "node-b", "state": "up:standby"}],
                "filesystems": [
                    {
                        "mdsmap": {
                            "info": {
                                "1": {"name": "node-a", "state": "up:active"}
                            }
                        }
                    }
                ],
            }
        }
    )

    assert placement_status.control_service_presence(mon, mgr, mds, "node-a") == {
        "mon": True,
        "mgr": True,
        "mds": True,
    }
    assert placement_status.control_service_presence(mon, mgr, mds, "node-c") == {
        "mon": False,
        "mgr": False,
        "mds": False,
    }


def test_control_service_presence_malformed_raises():
    # Unparseable output must not be reported as "service absent": an absence
    # assertion would otherwise pass on garbage rather than a genuine removal.
    import pytest as _pytest

    mon = json.dumps({"quorum_names": ["node-a"]})
    mgr = json.dumps([{"name": "node-a"}])
    mds = json.dumps({"fsmap": {"standbys": [], "filesystems": []}})

    for bad_mon, bad_mgr, bad_mds in (
        ("bad", mgr, mds),
        (mon, "bad", mds),
        (mon, mgr, "bad"),
        ("", "", ""),
    ):
        with _pytest.raises(ValueError):
            placement_status.control_service_presence(
                bad_mon, bad_mgr, bad_mds, "node-a"
            )


def test_member_in_ceph_status_substring():
    status = "  services:\n    mon: 2 daemons, quorum node-wrk0,node-wrk1\n"
    assert placement_status.member_in_ceph_status(status, "node-wrk1") is True
    assert placement_status.member_in_ceph_status(status, "node-wrk3") is False
    assert placement_status.member_in_ceph_status("", "node-wrk0") is False
    assert placement_status.member_in_ceph_status(None, "node-wrk0") is False


import pytest


# ---------------------------------------------------------------------------
# _poll_until failure semantics
# ---------------------------------------------------------------------------

def test_poll_until_callable_fail_msg_folds_in_last_value():
    seen = {"n": 0}

    def predicate():
        seen["n"] = 2
        return False

    with pytest.raises(AssertionError) as exc:
        H._poll_until(predicate, attempts=1, interval=0,
                      fail_msg=lambda: f"never reached 3 (last saw {seen['n']})")
    assert "last saw 2" in str(exc.value)


def test_poll_until_string_fail_msg_still_works():
    with pytest.raises(AssertionError) as exc:
        H._poll_until(lambda: False, attempts=1, interval=0, fail_msg="static message")
    assert str(exc.value) == "static message"


def test_poll_until_raising_on_fail_does_not_replace_fail_msg():
    def raising_on_fail():
        raise AssertionError("ceph -s cannot connect to cluster")

    with pytest.raises(AssertionError) as exc:
        H._poll_until(lambda: False, attempts=1, interval=0,
                      fail_msg="Never reached 3 OSD(s)", on_fail=raising_on_fail)
    assert str(exc.value) == "Never reached 3 OSD(s)"


def test_poll_until_success_never_evaluates_fail_msg_or_on_fail():
    calls = {"on_fail": 0}
    H._poll_until(lambda: True, attempts=3, interval=0,
                  fail_msg=lambda: 1 / 0, on_fail=lambda: calls.__setitem__("on_fail", 1))
    assert calls["on_fail"] == 0


# ---------------------------------------------------------------------------
# _echo_cmd / _log_exec -- command tracing routes to console (bash -x style)
# unless quiet: the command before it runs, its output after.
# ---------------------------------------------------------------------------

import microceph_harness as _mh
from collections import namedtuple as _nt

_Res = _nt("Res", ["rc", "stdout", "stderr"])


class _CapLogger:
    def __init__(self):
        self.console_lines = []
        self.info_lines = []

    def console(self, s):
        self.console_lines.append(s)

    def info(self, s):
        self.info_lines.append(s)

    def warn(self, s):
        self.info_lines.append("WARN:" + s)


def _with_logger(monkeypatch):
    cap = _CapLogger()
    monkeypatch.setattr(_mh, "logger", cap)
    return cap


def test_echo_cmd_prints_the_command(monkeypatch):
    cap = _with_logger(monkeypatch)
    H()._echo_cmd("microceph.ceph -s", quiet=False)
    assert cap.console_lines == ["+ microceph.ceph -s"]


def test_echo_cmd_quiet_prints_nothing(monkeypatch):
    cap = _with_logger(monkeypatch)
    H()._echo_cmd("microceph.ceph -s -f json", quiet=True)
    assert cap.console_lines == []


def test_log_exec_echoes_output_to_console(monkeypatch):
    cap = _with_logger(monkeypatch)
    H()._log_exec("microceph.ceph -s", _Res(0, "  cluster:\n    health: HEALTH_OK\n", ""), quiet=False)
    assert "health: HEALTH_OK" in "\n".join(cap.console_lines)


def test_log_exec_quiet_keeps_console_clean(monkeypatch):
    cap = _with_logger(monkeypatch)
    H()._log_exec("microceph.ceph -s -f json", _Res(0, '{"osdmap": {}}', ""), quiet=True)
    assert cap.console_lines == []
    # still captured in log.html (logger.info)
    assert any("microceph.ceph -s -f json" in s for s in cap.info_lines)


def test_log_exec_no_output_prints_nothing(monkeypatch):
    cap = _with_logger(monkeypatch)
    H()._log_exec("mkdir -p ~/x", _Res(0, "", ""), quiet=False)
    assert cap.console_lines == []

# ---------------------------------------------------------------------------
# wait_for_member_control_services (polling absence/presence with convergence)
# ---------------------------------------------------------------------------

def _harness_with_observations(monkeypatch, observations):
    """Return a harness whose _observe_control_services yields *observations*
    in order (the last value repeats once exhausted), counting calls."""
    h = H()
    seq = list(observations)
    state = {"calls": 0}

    def fake_observe(member):
        idx = min(state["calls"], len(seq) - 1)
        state["calls"] += 1
        return seq[idx]

    monkeypatch.setattr(h, "_observe_control_services", fake_observe)
    # Avoid real sleeps between probes.
    monkeypatch.setattr(_mh.time, "sleep", lambda *_: None)
    return h, state


def test_wait_for_control_services_absent_after_convergence(monkeypatch):
    # mgr lingers for the first two probes, then converges to fully absent.
    observations = [
        {"mon": False, "mgr": True, "mds": False},
        {"mon": False, "mgr": True, "mds": False},
        {"mon": False, "mgr": False, "mds": False},
    ]
    h, state = _harness_with_observations(monkeypatch, observations)
    h.wait_for_member_control_services("node-wrk1", "no", tries=10, interval=0)
    assert state["calls"] == 3


def test_wait_for_control_services_present_immediately(monkeypatch):
    observations = [{"mon": True, "mgr": True, "mds": True}]
    h, state = _harness_with_observations(monkeypatch, observations)
    h.wait_for_member_control_services("node-wrk0", "yes", tries=5, interval=0)
    assert state["calls"] == 1


def test_wait_for_control_services_absent_timeout_folds_last_observed(monkeypatch):
    observations = [{"mon": False, "mgr": True, "mds": False}]
    h, _ = _harness_with_observations(monkeypatch, observations)
    with pytest.raises(AssertionError) as exc:
        h.wait_for_member_control_services("node-wrk1", "no", tries=3, interval=0)
    msg = str(exc.value)
    assert "never became absent" in msg
    assert "'mgr': True" in msg


def test_wait_for_control_services_absent_ignores_unparseable_then_converges(monkeypatch):
    # Bad/empty Ceph output (ValueError) must NOT be treated as absence: the
    # poll keeps going until a genuine all-absent reading arrives.
    h = H()
    seq = [
        ValueError("unparseable mds stat output: ''"),
        {"mon": False, "mgr": True, "mds": False},
        {"mon": False, "mgr": False, "mds": False},
    ]
    state = {"calls": 0}

    def fake_observe(member):
        idx = min(state["calls"], len(seq) - 1)
        state["calls"] += 1
        result = seq[idx]
        if isinstance(result, Exception):
            raise result
        return result

    monkeypatch.setattr(h, "_observe_control_services", fake_observe)
    monkeypatch.setattr(_mh.time, "sleep", lambda *_: None)
    h.wait_for_member_control_services("node-wrk1", "no", tries=10, interval=0)
    assert state["calls"] == 3


def test_wait_for_control_services_absent_timeout_on_persistent_bad_output(monkeypatch):
    # Unparseable output that never recovers must time out (fail), never pass.
    h = H()

    def fake_observe(member):
        raise ValueError("unparseable mds stat output: ''")

    monkeypatch.setattr(h, "_observe_control_services", fake_observe)
    monkeypatch.setattr(_mh.time, "sleep", lambda *_: None)
    with pytest.raises(AssertionError) as exc:
        h.wait_for_member_control_services("node-wrk1", "no", tries=3, interval=0)
    msg = str(exc.value)
    assert "never became absent" in msg
    assert "unparseable" in msg


# ---------------------------------------------------------------------------
# rgw_replication.py pure helpers
# ---------------------------------------------------------------------------


def test_parse_rgw_replication_status_string_metadata():
    # The ops API wraps the handler's JSON document as a string in the
    # microcluster envelope; both decodes must happen.
    doc = {"realm": "verify", "zone": "us-east", "data_sync": []}
    raw = json.dumps({"type": "sync", "status": "Success", "metadata": json.dumps(doc)})
    assert parse_rgw_replication_status(raw) == doc


def test_parse_rgw_replication_status_dict_metadata():
    # Tolerate a future server that stops string-encoding the document.
    doc = {"realm": "verify"}
    raw = json.dumps({"metadata": doc})
    assert parse_rgw_replication_status(raw) == doc


def test_parse_rgw_replication_status_rejects_no_document():
    # An error envelope or non-JSON body must fail, never read as empty status.
    with pytest.raises(AssertionError):
        parse_rgw_replication_status(json.dumps({"error": "boom", "metadata": ""}))
    with pytest.raises(AssertionError):
        parse_rgw_replication_status("not json at all")
    with pytest.raises(AssertionError):
        parse_rgw_replication_status(json.dumps({"metadata": "not json either"}))


def test_rgw_data_sync_states():
    status = {
        "data_sync": [
            {"source_zone": "us-west", "state": "local-unavailable"},
            {"source_zone": "us-archive", "state": "not-a-source"},
        ]
    }
    assert rgw_data_sync_states(status) == {
        "us-west": "local-unavailable",
        "us-archive": "not-a-source",
    }
    assert rgw_data_sync_states({}) == {}
    assert rgw_data_sync_states({"data_sync": None}) == {}
