package ceph

import (
	"text/template"
)

var cephConfTpl = template.Must(template.New("cephConf").Parse(`# # Generated by MicroCeph, DO NOT EDIT.
[global]
run dir = {{.runDir}}
fsid = {{.fsid}}
mon host = {{.monitors}}
auth allow insecure global id reclaim = false
public addr = {{.addr}}
`))

var cephKeyringTpl = template.Must(template.New("cephKeyring").Parse(`# Generated by MicroCeph, DO NOT EDIT.
[{{.name}}]
	key = {{.key}}
`))
