name: Main Documentation Checks

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "docs/**" # Only run on changes to the docs directory
  workflow_dispatch:
    # Manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@main
    with:
      working-directory: "docs"
      fetch-depth: 0

  openapi-check:
    name: OpenAPI Spec Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: pip install openapi-spec-validator

      - name: Check spec
        run: |
          set -eux
          openapi-spec-validator ./docs/openapi/openapi.yaml
