#!/bin/sh -eux

# disable all services
for svc in $(snapctl services |awk '/enabled/{print$1}'); do
    snapctl stop --disable $svc
done

# pre-create the directory layout expected by the Ceph daemons
mkdir -p $SNAP_COMMON/etc/ceph
mkdir -p $SNAP_COMMON/var/run/ceph
for ceph_daemon in mds mgr osd rbd rbd-mirror rgw; do
    mkdir -p $SNAP_COMMON/var/lib/ceph/bootstrap-$ceph_daemon
    if [ "$ceph_daemon" = rgw ]; then
        mkdir -p $SNAP_COMMON/var/lib/ceph/radosgw
    else
        mkdir -p $SNAP_COMMON/var/lib/ceph/$ceph_daemon
    fi
done
mkdir -p $SNAP_COMMON/var/lib/ceph/crash/posted
mkdir -p $SNAP_COMMON/var/log/ceph
